// AUTO-GENERATED by train-model.ts — do not edit manually
// Training data: SWE-bench Verified (Claude models, bash-only track)
// Date: 2026-03-04T20:07:24.817Z
// N_train: 1800, N_calibration: 600

export interface TrainedModelWeights {
  featureNames: string[];
  models: Record<string, {
    beta: number[];
    rSquared: number;
    conformalQuantiles: Record<string, number>;
    trainMeanLogCost: number;
    trainStdLogCost: number;
  }>;
  global: {
    beta: number[];
    rSquared: number;
    conformalQuantiles: Record<string, number>;
  };
}

export const MODEL_WEIGHTS: TrainedModelWeights = {
  "featureNames": [
    "logCharCount",
    "wordCount",
    "lineCount",
    "sentenceCount",
    "codeBlockCount",
    "filePathCount",
    "functionNameCount",
    "classNameCount",
    "hasStackTrace",
    "hasErrorMsg",
    "vocabRichness",
    "technicalDensity",
    "avgLineLength",
    "maxLineLength",
    "mentionsFix",
    "mentionsAdd",
    "mentionsRefactor",
    "mentionsTest",
    "mentionsDeprecation",
    "mentionsRegression",
    "mentionsPerformance",
    "questionCount",
    "urlCount",
    "codeRefCount"
  ],
  "models": {
    "opus": {
      "beta": [
        -0.58341,
        0.141,
        -0.00064,
        0.00077,
        0.00462,
        -0.026,
        -0.0088,
        -0.00083,
        0.00356,
        -0.11021,
        -0.01115,
        -0.24309,
        0.89279,
        -0.00105,
        0.00019,
        -0.09027,
        0.10255,
        -0.01822,
        0.11605,
        0.07094,
        0.03908,
        -0.12476,
        -0.01186,
        -0.01703,
        0.0006
      ],
      "rSquared": 0.1658,
      "conformalQuantiles": {
        "50": 0.2222,
        "60": 0.2872,
        "70": 0.353,
        "75": 0.3955,
        "80": 0.4387,
        "85": 0.4766,
        "90": 0.5499,
        "95": 0.7283
      },
      "trainMeanLogCost": -0.3093,
      "trainStdLogCost": 0.3257
    },
    "sonnet": {
      "beta": [
        -0.66739,
        0.10517,
        -0.00044,
        0.00099,
        0.00268,
        -0.02489,
        -0.00694,
        0.00108,
        0.00712,
        -0.05316,
        -0.00688,
        0.02271,
        0.4615,
        -0.00016,
        0.00019,
        -0.05059,
        0.06431,
        -0.09702,
        0.05967,
        -0.00389,
        0.0092,
        -0.05487,
        -0.014,
        -0.00707,
        0.0006
      ],
      "rSquared": 0.1694,
      "conformalQuantiles": {
        "50": 0.147,
        "60": 0.1925,
        "70": 0.221,
        "75": 0.2398,
        "80": 0.2731,
        "85": 0.3084,
        "90": 0.3811,
        "95": 0.455
      },
      "trainMeanLogCost": -0.2764,
      "trainStdLogCost": 0.2096
    },
    "haiku": {
      "beta": [
        -1.01038,
        0.16219,
        -0.00055,
        0.00149,
        0.00308,
        -0.01877,
        -0.01181,
        -0.00025,
        0.01137,
        -0.04893,
        0.01548,
        -0.09707,
        0.25587,
        0.00005,
        0.00004,
        -0.07849,
        0.08946,
        -0.14835,
        0.12543,
        0.0451,
        0.05163,
        -0.04623,
        -0.01051,
        -0.01618,
        -0.00082
      ],
      "rSquared": 0.2097,
      "conformalQuantiles": {
        "50": 0.2018,
        "60": 0.2366,
        "70": 0.2743,
        "75": 0.3184,
        "80": 0.3524,
        "85": 0.4055,
        "90": 0.4923,
        "95": 0.6328
      },
      "trainMeanLogCost": -0.5542,
      "trainStdLogCost": 0.2561
    }
  },
  "global": {
    "beta": [
      -0.72202,
      0.13187,
      -0.00056,
      0.00096,
      0.00372,
      -0.02443,
      -0.00867,
      -0.00011,
      0.00607,
      -0.08111,
      -0.00532,
      -0.13035,
      0.65487,
      -0.00057,
      0.00016,
      -0.07507,
      0.08768,
      -0.0661,
      0.09881,
      0.04165,
      0.03126,
      -0.08835,
      -0.0124,
      -0.01361,
      0.00035,
      0.07065,
      0.10357,
      -0.17423
    ],
    "rSquared": 0.2499,
    "conformalQuantiles": {
      "50": 0.1962,
      "60": 0.2384,
      "70": 0.2981,
      "75": 0.331,
      "80": 0.3652,
      "85": 0.4266,
      "90": 0.4875,
      "95": 0.6347
    }
  }
};
